api:
  http:
    server: http://umcdev3.ubivelox.com:10200
mqtt:
  app:
    topic:
      name: /thingseye/app
  auth:
    password: thingseye123$
    username: thingseye2
  http:
    server: http://218.55.23.203:18083
  iot:
    topic:
      name: /thingseye/iot
  node:
    name: emqx@218.55.23.203
  tcp:
    urls: tcp://218.55.23.203:1883
  topic:
    name: /thingseye
server:
  port: 18080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: thingseye2123$
    url: jdbc:mysql://218.55.23.178:23306/thingseye2_dev?useSSL=false    
    username: thingseye2
  profiles:
    active: '@activatedProperties@'
  redis:
    host: 218.55.23.203
    port: 6379
    timeout: 10000
thingseye:
  event:
    queue: thingseye:queue:event
  push:
    queue: thingseye:queue:push0
  user:
    auth: thingseye:auth:user
uuid:
  aes:
    key: 12345thingseye167890
